### ISSUE TITLE
Wrong coordinate sign on page 3 of Learning Activities 4.2?

### ISSUE THREAD

**Issue by mahbubasif** [AaronWongNSC/Math127#1]
Hey,
Isn't the sign convention on 3rd diagram of 5th problem in 4.2 be negative? I am is not it (-4/sqrt(65), -7/sqrt(65)? As in the third quadrant the sign convention is (-, -). 
Thanks

**Comment by AaronWongNSC** [comment]
You are correct! Thanks for catching that! Sorry for being really slow to notice that you raised this issue, but I've actually moved on to make a better set of notes and videos.

https://github.com/AaronWongNSC/Trigonometry
